# Generated by Django 3.2.3 on 2021-05-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprime_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gprimepropertyfeature',
            name='bathroom',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
