# Generated by Django 3.2.3 on 2021-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gprime_properties', '0002_alter_gprimepropertyfeature_bathroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='gprimepropertyfeature',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gprimepropertyfeature',
            name='halls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gprimepropertyfeature',
            name='kitchen',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gprimepropertyfeature',
            name='swimming_pools',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gprimepropertyfeature',
            name='toilets',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
